import React, { useState, useEffect } from 'react';
import { Book } from '../types';
import { ChevronLeftIcon, ChevronRightIcon, XIcon, BookOpenIcon, DownloadIcon } from './icons';
import { jsPDF } from 'jspdf';

interface BookReaderProps {
    book: Book;
    onClose: () => void;
}

const BookReader: React.FC<BookReaderProps> = ({ book, onClose }) => {
    const [currentChapter, setCurrentChapter] = useState(0);
    const [fontSize, setFontSize] = useState(18);
    const [showExportMenu, setShowExportMenu] = useState(false);

    // Scroll to top when chapter changes
    useEffect(() => {
        const contentArea = document.getElementById('book-content-area');
        if (contentArea) contentArea.scrollTop = 0;
    }, [currentChapter]);

    const handleExportPDF = () => {
        const doc = new jsPDF();

        // Title Page
        doc.setFontSize(24);
        doc.text(book.title || 'Untitled Story', 105, 100, { align: 'center' });
        doc.setFontSize(12);
        doc.text('Generated by StoryWeaver', 105, 110, { align: 'center' });

        book.chapters.forEach((chapter, index) => {
            doc.addPage();
            doc.setFontSize(18);
            doc.text(`Chapter ${index + 1}: ${chapter.title}`, 20, 20);

            doc.setFontSize(12);
            const splitText = doc.splitTextToSize(chapter.content || '', 170);
            doc.text(splitText, 20, 30);
        });

        doc.save(`${book.title || 'story'}.pdf`);
        setShowExportMenu(false);
    };

    const handleExportText = () => {
        let textContent = `${book.title || 'Untitled Story'}\n\n`;

        book.chapters.forEach((chapter, index) => {
            textContent += `Chapter ${index + 1}: ${chapter.title}\n`;
            textContent += `${'-'.repeat(20)}\n`;
            textContent += `${chapter.content || ''}\n\n`;
            textContent += `${'='.repeat(20)}\n\n`;
        });

        const blob = new Blob([textContent], { type: 'text/plain' });
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = `${book.title || 'story'}.txt`;
        document.body.appendChild(a);
        a.click();
        document.body.removeChild(a);
        URL.revokeObjectURL(url);
        setShowExportMenu(false);
    };

    if (!book.chapters || book.chapters.length === 0) {
        return (
            <div className="absolute inset-0 z-50 bg-brand-bg flex items-center justify-center">
                <div className="text-center p-8">
                    <p className="text-brand-text-muted mb-4">No chapters found in this book.</p>
                    <button onClick={onClose} className="px-4 py-2 bg-brand-secondary text-white rounded-lg">Close</button>
                </div>
            </div>
        )
    }

    return (
        <div className="absolute inset-0 z-50 bg-brand-bg flex flex-col animate-in zoom-in-95 duration-300">
            {/* Header */}
            <div className="flex items-center justify-between p-4 border-b border-white/10 bg-brand-surface/80 backdrop-blur-md z-20">
                <div className="flex items-center gap-3">
                    <BookOpenIcon className="w-6 h-6 text-brand-secondary" />
                    <div>
                        <h2 className="font-serif font-bold text-lg text-brand-text leading-tight">{book.title || 'Untitled Story'}</h2>
                        <p className="text-xs text-brand-text-muted">Chapter {currentChapter + 1} of {book.chapters.length}</p>
                    </div>
                </div>
                <div className="flex items-center gap-4">
                    <div className="relative">
                        <button
                            onClick={() => setShowExportMenu(!showExportMenu)}
                            className="flex items-center gap-2 px-3 py-1.5 bg-white/5 hover:bg-white/10 rounded-lg text-brand-text-muted hover:text-white transition text-sm font-medium"
                        >
                            <DownloadIcon className="w-4 h-4" />
                            <span className="hidden sm:inline">Export</span>
                        </button>

                        {showExportMenu && (
                            <div className="absolute top-full right-0 mt-2 w-48 bg-brand-surface border border-white/10 rounded-xl shadow-xl overflow-hidden z-50 animate-in fade-in zoom-in-95 duration-200">
                                <button onClick={handleExportPDF} className="w-full text-left px-4 py-3 hover:bg-white/5 text-brand-text text-sm flex items-center gap-2">
                                    <span className="font-bold text-red-400">PDF</span> Document
                                </button>
                                <button onClick={handleExportText} className="w-full text-left px-4 py-3 hover:bg-white/5 text-brand-text text-sm flex items-center gap-2 border-t border-white/5">
                                    <span className="font-bold text-blue-400">TXT</span> Plain Text
                                </button>
                            </div>
                        )}
                    </div>

                    <div className="hidden md:flex items-center gap-2 bg-white/5 rounded-lg p-1">
                        <button onClick={() => setFontSize(Math.max(14, fontSize - 2))} className="w-8 h-8 flex items-center justify-center text-brand-text-muted hover:text-white font-serif text-sm">A-</button>
                        <button onClick={() => setFontSize(Math.min(28, fontSize + 2))} className="w-8 h-8 flex items-center justify-center text-brand-text-muted hover:text-white font-serif text-lg">A+</button>
                    </div>
                    <button onClick={onClose} className="p-2 text-brand-text-muted hover:text-white transition rounded-full hover:bg-white/10">
                        <XIcon className="w-6 h-6" />
                    </button>
                </div>
            </div>

            {/* Content */}
            <div id="book-content-area" className="flex-grow overflow-y-auto custom-scrollbar p-4 md:p-12 bg-brand-bg relative" onClick={() => setShowExportMenu(false)}>
                <div className="max-w-3xl mx-auto bg-brand-surface/30 p-8 md:p-16 rounded-lg shadow-2xl min-h-full border border-white/5">
                    <div className="mb-12 text-center">
                        <span className="text-brand-secondary text-xs font-bold uppercase tracking-[0.2em] mb-2 block">Chapter {currentChapter + 1}</span>
                        <h3 className="font-serif text-3xl md:text-4xl font-bold text-brand-text">{book.chapters[currentChapter].title}</h3>
                        <div className="w-16 h-1 bg-brand-secondary/50 mx-auto mt-6 rounded-full"></div>
                    </div>

                    <div
                        className="prose prose-invert prose-lg max-w-none font-serif leading-loose text-brand-text/90 whitespace-pre-wrap"
                        style={{ fontSize: `${fontSize}px` }}
                    >
                        {book.chapters[currentChapter].content || <span className="italic opacity-50">This scene has no text yet.</span>}
                    </div>

                    <div className="mt-16 flex justify-center">
                        <span className="text-brand-text-muted text-2xl opacity-50">***</span>
                    </div>
                </div>
            </div>

            {/* Footer / Nav */}
            <div className="p-4 border-t border-white/10 bg-brand-surface/80 backdrop-blur-md flex justify-between items-center z-20">
                <button
                    onClick={() => setCurrentChapter(Math.max(0, currentChapter - 1))}
                    disabled={currentChapter === 0}
                    className="flex items-center gap-2 px-4 py-3 rounded-xl hover:bg-white/10 disabled:opacity-30 disabled:cursor-not-allowed text-brand-text font-medium transition"
                >
                    <ChevronLeftIcon className="w-5 h-5" />
                    <span className="hidden sm:inline">Previous</span>
                </button>

                <div className="h-1.5 w-32 md:w-64 bg-white/10 rounded-full overflow-hidden">
                    <div
                        className="h-full bg-brand-secondary transition-all duration-300 ease-out"
                        style={{ width: `${((currentChapter + 1) / book.chapters.length) * 100}%` }}
                    />
                </div>

                <button
                    onClick={() => setCurrentChapter(Math.min(book.chapters.length - 1, currentChapter + 1))}
                    disabled={currentChapter === book.chapters.length - 1}
                    className="flex items-center gap-2 px-4 py-3 rounded-xl hover:bg-white/10 disabled:opacity-30 disabled:cursor-not-allowed text-brand-text font-medium transition"
                >
                    <span className="hidden sm:inline">Next</span>
                    <ChevronRightIcon className="w-5 h-5" />
                </button>
            </div>
        </div>
    );
}

export default BookReader;